name: Update README cards

on:
  schedule:
    - cron: "0 23 * * *" # codziennie o 23:00 CET
  workflow_dispatch:       # możliwość ręcznego uruchomienia

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # potrzebne do commitowania i pushowania zmian

    steps:

      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.GH_PAT }}

      - name: Commit cards if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/stats.svg
          # jeśli są zmiany, commit i push
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Update README cards"
            git push
